apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver-80
  namespaces: default
spec:
  ingressClassName: nginx
  rules:
    - host: httpserver.cmcamp.com
      http:
        paths:
          - backend:
              service:
                name: httpsvc
                port:
                  number: 80
            path: /
            pathType: Prefix